name: build

on: [push, pull_request]

jobs:
  gcc:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        compiler: [gcc5, gcc6, gcc7, gcc8, gcc9, gcc10]
        flavor: [Debug, Release]
        arch: [x86, x64]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup compiler
        run: ./tools/setup_compiler.sh
      - name: Building ${{ matrix.flavor }}-${{ matrix.arch }} with ${{ matrix.compiler }}
        run: python3 make.py -build -compiler ${{ matrix.compiler }} -config ${{ matrix.flavor }} -cpu ${{ matrix.arch }}
      - name: Running unit tests
        run: python3 make.py -unit_test -compiler ${{ matrix.compiler }} -config ${{ matrix.flavor }} -cpu ${{ matrix.arch }}
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Cache emsdk
        uses: actions/cache@v1
        id: 'emsdk'
        with:
          path: 'emsdk-cache'
          key: ${{ runner.os }}-emsdk-1.39.11
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: 1.39.11
          no-cache: true
          actions-cache-folder: 'emsdk-cache'
      - name: Cache emsdk build artifacts
        uses: actions/cache@v1
        id: 'emsdk-build-artifacts'
        with:
          path: '~/.emscripten_cache'
          key: ${{ runner.os }}-emsdk-build-artifacts-1.39.11
      - name: Building (debug)
        run: python3 make.py -compiler emscripten -config debug -build
      - name: Running unit tests (debug)
        run: python3 make.py -compiler emscripten -config debug -unit_test
      - name: Clean
        run: python3 make.py -clean
      - name: Building (release)
        run: python3 make.py -compiler emscripten -config release -build
      - name: Running unit tests (release)
        run: python3 make.py -compiler emscripten -config release -unit_test
