name: test cpp versions

on:
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc13, clang18]
        cpp_version: [14, 17, 20]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Building (release-x86)
        uses: docker://ghcr.io/nfrechette/toolchain-amd64-lunar:v2
        with:
          args: 'python3 make.py -ci -compiler ${{ matrix.compiler }} -config Release -cpu x86 -cpp_version ${{ matrix.cpp_version }} -build'
      - name: Clean
        uses: docker://ghcr.io/nfrechette/toolchain-amd64-lunar:v2
        with:
          args: 'python3 make.py -clean_only'
      - name: Building (release-x64)
        uses: docker://ghcr.io/nfrechette/toolchain-amd64-lunar:v2
        with:
          args: 'python3 make.py -ci -compiler ${{ matrix.compiler }} -config Release -cpu x64 -cpp_version ${{ matrix.cpp_version }} -build'

  vs2022:
    runs-on: windows-2022
    strategy:
      matrix:
        cpp_version: [14, 17, 20]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Building (release-x86)
        run: python3 make.py -ci -compiler vs2022 -config Release -cpu x86 -cpp_version ${{ matrix.cpp_version }} -build
      - name: Clean
        run: python3 make.py -clean_only
      - name: Building (release-x64)
        run: python3 make.py -ci -compiler vs2022 -config Release -cpu x64 -cpp_version ${{ matrix.cpp_version }} -build
      - name: Clean
        run: python3 make.py -clean_only
      - name: Building (release-arm64)
        run: python3 make.py -ci -compiler vs2022 -config Release -cpu arm64 -cpp_version ${{ matrix.cpp_version }} -build
